In [ ]:
import pandas as pd

In [ ]:
df = pd.read_json('full_raw_bat.ndjson', lines=True)
df = df.head(25)
df.to_csv("gifs_to_form.csv", index=False)

<hr>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import time
import pandas as pd

In [2]:
df = pd.read_csv("gifs_to_form.csv")
df

,word,countrycode,timestamp,recognized,key_id,drawing
0,bat,RO,2017-03-07 14:44:14.700630+00:00,True,5073402912047104,"[[[665, 661, 658, 653, 644, 640, 632, 629, 625..."
1,bat,US,2017-03-15 17:34:06.077310+00:00,False,5620429609762816,"[[[649, 649, 649, 649, 649, 649, 649, 649, 649..."
2,bat,BR,2017-01-28 01:55:34.355190+00:00,True,4693878131130368,"[[[110.2300033569336, 110.89800262451172, 112...."
3,bat,US,2017-03-10 17:42:01.807820+00:00,False,6480660153761792,"[[[292, 297, 303, 315, 323, 326, 330, 339, 357..."
4,bat,AU,2017-03-23 01:13:11.993780+00:00,True,6365214737956864,"[[[600, 593, 584, 579, 572, 569, 566, 564, 562..."
5,bat,CA,2017-03-07 12:24:44.452690+00:00,True,6623797522202624,"[[[1249, 1252, 1254, 1256, 1257, 1257, 1257, 1..."
6,bat,US,2017-03-01 22:37:37.691380+00:00,True,5414885192105984,"[[[746, 739, 732, 723, 712, 698, 687, 682, 673..."
7,bat,US,2017-03-29 16:40:07.896660+00:00,True,6589479475216384,"[[[637, 631, 627, 622, 618, 615, 611, 609, 607..."
8,bat,US,2017-03-28 15:01:16.751000+00:00,True,4679241096495104,"[[[896, 891, 885, 880, 872, 863, 852, 836, 817..."
9,bat,SI,2017-03-26 22:16:12.093150+00:00,True,5501267503742976,"[[[938, 940, 941, 941, 943, 944, 944, 946, 946..."
10,bat,US,2017-03-08 17:52:43.695480+00:00,True,4936622430748672,"[[[435, 436, 436, 436, 436, 436, 435, 435, 435..."
11,bat,MY,2017-03-28 14:21:53.096960+00:00,True,6315771342880768,"[[[881, 873, 865, 859, 852, 845, 837, 829, 823..."
12,bat,US,2017-01-30 18:03:33.631730+00:00,True,6590702588788736,"[[[681, 674, 669, 663, 658, 652, 642, 638, 636..."
13,bat,IT,2017-03-04 19:12:26.177760+00:00,True,6220997101355008,"[[[871, 871, 871, 870, 870, 869, 869, 869, 869..."
14,bat,US,2017-03-01 18:19:41.824480+00:00,True,6408054906028032,"[[[169, 168, 169, 169, 171, 172, 175, 178, 182..."
15,bat,RO,2017-03-10 08:03:27.426240+00:00,True,6212311939284992,"[[[135.33299255371094, 135.33299255371094, 137..."
16,bat,MX,2017-03-27 03:43:11.754560+00:00,True,5083275582242816,"[[[887, 888, 888, 888, 887, 885, 884, 882, 881..."
17,bat,US,2017-03-07 15:20:20.612240+00:00,True,5135211517968384,"[[[143, 134, 126, 118, 110, 98, 88, 77, 67, 59..."
18,bat,US,2017-03-25 00:26:24.524970+00:00,True,4572827711700992,"[[[490, 479, 470, 463, 455, 449, 446, 445, 447..."
19,bat,PT,2017-03-28 15:41:41.457840+00:00,True,6020450935111680,"[[[602, 597, 592, 586, 574, 565, 555, 547, 538..."
20,bat,JP,2017-01-29 10:44:54.905810+00:00,True,4807280702783488,"[[[790, 787, 783, 779, 776, 774, 773, 774, 777..."
21,bat,US,2017-01-27 17:05:31.002180+00:00,True,4637080409866240,"[[[454, 453, 445, 437, 429, 421, 411, 402, 392..."
22,bat,ES,2017-01-24 14:18:45.446730+00:00,True,6128674803810304,"[[[950, 945, 937, 932, 926, 916, 911, 902, 882..."
23,bat,US,2017-03-07 13:08:43.529800+00:00,True,6049667634692096,"[[[390, 388, 388, 388, 388, 387, 387, 387, 386..."
24,bat,GB,2017-03-01 13:35:11.697590+00:00,False,6688457751527424,"[[[806, 801, 794, 789, 784, 778, 773, 767, 761..."

In [ ]:
import os

for j in range(len(df)):
    s = pd.DataFrame(eval(df.iloc[j]["drawing"]))
    x_min, x_max = s.loc[:,0].map(min).min(), s.loc[:,0].map(max).max()
    y_min, y_max = s.loc[:,1].map(min).min(), s.loc[:,1].map(max).max()

    for row_idx in range(len(s)):
        rows = s.iloc[:row_idx+1]
        fig = plt.figure(figsize=((x_max - x_min)/100, (y_max - y_min)/100))
        for row_iter in range(len(rows)):
            row = rows.iloc[row_iter]
            for i in range(1, len(row[0])):
                for k in range(1,i):
                    plt.plot([(row[0][k-1]-x_min)/100, (row[0][k]-x_min)/100], [(row[1][k-1]-y_min)/100, (row[1][k]-y_min)/100], linestyle='-', color="black")
                plt.axis('off')
                plt.xlim(0, (x_max-x_min)/100)
                plt.ylim(0, (y_max-y_min)/100)
                if not os.path.exists(f"./bat_images/bat_{j}"):
                    os.makedirs(f"./bat_images/bat_{j}")
                plt.savefig(f"./bat_images/bat_{j}/frame_{row_iter}_{i}.jpg")

<hr>

In [5]:
import glob
import imageio

In [10]:
for i in range(6):
    anim_file = f'./bat_{i}.gif'

    with imageio.get_writer(anim_file, mode='I') as writer:
      filenames = glob.glob(f'./bat_images/bat_{i}/frame*.jpg')
      filenames = sorted(filenames)
      for filename in filenames:
        image = imageio.imread(filename)
        writer.append_data(image)
      image = imageio.imread(filename)
      writer.append_data(image)

C:\Users\chyav\AppData\Local\Temp\ipykernel_22992\2936634630.py:8: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  image = imageio.imread(filename)
C:\Users\chyav\AppData\Local\Temp\ipykernel_22992\2936634630.py:10: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  image = imageio.imread(filename)